# Generated by Django 4.0.3 on 2023-08-07 12:25

from django.db import migrations, models
import zimmyrabbit.models


class Migration(migrations.Migration):

    dependencies = [
        ('zimmyrabbit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhist',
            name='env',
            field=models.CharField(default='dev', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildhist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildhist',
            name='lastupdt',
            field=models.DateTimeField(default=zimmyrabbit.models.BuildHist.get_current_time),
        ),
        migrations.AlterUniqueTogether(
            name='buildhist',
            unique_together={('env', 'component')},
        ),
    ]
